version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    app:
        build: 
            context: ./
            dockerfile: Dockerfile
        image: laravel8-php-fpm-80
        container_name: servm_app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            - ./:/var/www
        networks: 
            - app-network
    
    mysql:
        image: mysql:5.7.33
        container_name: servm_mysql
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_DATABASE: servm
            MYSQL_ROOT_PASSWORD: password
            MYSQL_PASSWORD: password
            MYSQL_USER: user
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes: 
            - ./mysql/data:/var/lib/mysql
        networks:
            - app-network
    
    nginx:
        image: nginx:1.19.8-alpine
        container_name: servm_nginx
        restart: unless-stopped
        tty: true
        ports: 
            - 8100:80
        volumes: 
            - ./:/var/www
            - ./nginx/conf:/etc/nginx/conf.d
        networks: 
            - app-network

    npm: 
        image: node:17-alpine3.12
        container_name: servm_npm
        volumes: 
            - ./:/var/www
        working_dir: /var/www
        entrypoint: ['npm']
        command: "install"
        networks: 
            - app-network